addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"           % "1.4.3-23-550c6c0a")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.9.19"           )
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0"           )
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.4"            )
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1"            )
