addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"           % "1.4.8" )
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.9.26")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.0" )
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1" )
